# Generated by Django 5.1.2 on 2024-10-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur', models.CharField(max_length=50)),
                ('points_victoire', models.PositiveIntegerField()),
                ('bonus', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jeton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur', models.CharField(max_length=50)),
                ('quantite', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('points_victoire', models.PositiveIntegerField(default=0)),
                ('bonus', models.JSONField(default=dict)),
                ('cartes', models.ManyToManyField(related_name='joueurs', to='jeu.carte')),
                ('cartes_reservees', models.ManyToManyField(related_name='joueurs_reserves', to='jeu.carte')),
                ('jetons', models.ManyToManyField(related_name='joueurs', to='jeu.jeton')),
            ],
        ),
    ]
