# Generated by Django 5.1.2 on 2024-11-15 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.PositiveIntegerField()),
                ('cout', models.JSONField(default=dict)),
                ('bonus', models.CharField(max_length=50)),
                ('points_victoire', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Noble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('points_de_victoire', models.PositiveIntegerField()),
                ('cout', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CartePileNiveau1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeu.carte')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CartePileNiveau2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeu.carte')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CartePileNiveau3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeu.carte')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('nombre_joueurs', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('joueur_courant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties_en_cours', to=settings.AUTH_USER_MODEL)),
                ('joueurs', models.ManyToManyField(related_name='parties', to=settings.AUTH_USER_MODEL)),
                ('nobles', models.ManyToManyField(blank=True, related_name='parties', to='jeu.noble')),
            ],
        ),
        migrations.CreateModel(
            name='JoueurPartie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_victoire', models.IntegerField(default=0)),
                ('jetons', models.JSONField(default=dict)),
                ('bonus', models.JSONField(default=dict)),
                ('tokens_a_defausser', models.PositiveIntegerField(default=0)),
                ('cartes_achetees', models.ManyToManyField(blank=True, related_name='achetees', to='jeu.carte')),
                ('cartes_reservees', models.ManyToManyField(blank=True, related_name='reservees', to='jeu.carte')),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nobles_acquis', models.ManyToManyField(blank=True, related_name='joueurs', to='jeu.noble')),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='jeu.partie')),
            ],
        ),
        migrations.CreateModel(
            name='Plateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartes', models.ManyToManyField(related_name='cartes_visibles', to='jeu.carte')),
                ('cartes_pile_niveau_1_new', models.ManyToManyField(related_name='cartes_pile_niveau_1_new', through='jeu.CartePileNiveau1', to='jeu.carte')),
                ('cartes_pile_niveau_2_new', models.ManyToManyField(related_name='cartes_pile_niveau_2_new', through='jeu.CartePileNiveau2', to='jeu.carte')),
                ('cartes_pile_niveau_3_new', models.ManyToManyField(related_name='cartes_pile_niveau_3_new', through='jeu.CartePileNiveau3', to='jeu.carte')),
                ('partie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plateau', to='jeu.partie')),
            ],
        ),
        migrations.CreateModel(
            name='Jeton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur', models.CharField(max_length=50)),
                ('quantite', models.PositiveIntegerField()),
                ('max_quantite', models.IntegerField(default=7)),
                ('plateau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jetons', to='jeu.plateau')),
            ],
        ),
        migrations.AddField(
            model_name='cartepileniveau3',
            name='plateau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeu.plateau'),
        ),
        migrations.AddField(
            model_name='cartepileniveau2',
            name='plateau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeu.plateau'),
        ),
        migrations.AddField(
            model_name='cartepileniveau1',
            name='plateau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeu.plateau'),
        ),
    ]
