# Generated by Django 5.1.2 on 2024-11-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie',
            name='status',
            field=models.CharField(choices=[('ongoing', 'En cours'), ('final_turn', 'Tour final'), ('finished', 'Terminée')], default='ongoing', max_length=20),
        ),
    ]
