# Generated by Django 5.1.2 on 2024-11-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueurpartie',
            name='bonus',
            field=models.JSONField(default=dict),
        ),
    ]
