# Generated by Django 5.1.2 on 2024-11-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0002_joueurpartie_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joueurpartie',
            name='cartes_achetees',
        ),
        migrations.RemoveField(
            model_name='joueurpartie',
            name='cartes_reservees',
        ),
    ]
