# Generated by Django 5.1.2 on 2024-11-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0002_partie_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueurpartie',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='joueurpartie',
            unique_together={('partie', 'order')},
        ),
    ]
