# Generated by Django 5.1.2 on 2024-10-27 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0003_partie'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeton',
            name='partie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jetons', to='jeu.partie'),
        ),
    ]
