# Generated by Django 5.1.2 on 2024-10-27 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0004_jeton_partie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jeton',
            name='partie',
        ),
        migrations.CreateModel(
            name='Plateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plateau', to='jeu.partie')),
            ],
        ),
        migrations.AddField(
            model_name='jeton',
            name='plateau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jetons', to='jeu.plateau'),
        ),
    ]
