# Generated by Django 5.1.2 on 2024-10-27 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0005_remove_jeton_partie_plateau_jeton_plateau'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JoueurPartie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_victoire', models.IntegerField(default=0)),
                ('jetons', models.JSONField(default=dict)),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='jeu.partie')),
            ],
        ),
    ]
