# Generated by Django 5.1.2 on 2024-11-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0005_jeton_max_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueurpartie',
            name='tokens_a_defausser',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
