# Generated by Django 5.1.2 on 2024-11-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0006_joueurpartie_tokens_a_defausser'),
    ]

    operations = [
        migrations.AddField(
            model_name='plateau',
            name='cartes_pile_niveau_1',
            field=models.ManyToManyField(related_name='cartes_pile_niveau_1', to='jeu.carte'),
        ),
        migrations.AlterField(
            model_name='plateau',
            name='cartes',
            field=models.ManyToManyField(related_name='cartes_visibles', to='jeu.carte'),
        ),
    ]
