# Generated by Django 5.1.2 on 2024-10-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0006_joueurpartie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Joueur',
        ),
    ]
