# Generated by Django 5.1.2 on 2024-11-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0007_plateau_cartes_pile_niveau_1_alter_plateau_cartes'),
    ]

    operations = [
        migrations.AddField(
            model_name='plateau',
            name='cartes_pile_niveau_2',
            field=models.ManyToManyField(related_name='cartes_pile_niveau_2', to='jeu.carte'),
        ),
        migrations.AddField(
            model_name='plateau',
            name='cartes_pile_niveau_3',
            field=models.ManyToManyField(related_name='cartes_pile_niveau_3', to='jeu.carte'),
        ),
    ]
