# Generated by Django 5.1.2 on 2024-11-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0009_noble_joueurpartie_nobles_acquis'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie',
            name='nobles',
            field=models.ManyToManyField(blank=True, related_name='parties', to='jeu.noble'),
        ),
    ]
